### ISSUE TITLE
Organize learning games by topics & verify all learning game links are still valid

### ISSUE THREAD

**Issue by alisaduncan** [KansasCityWomeninTechnology/LearningResources#10]
The links in the [learning games section](https://github.com/KansasCityWomeninTechnology/LearningResources/blob/master/LearningResources.md#learn-coding-skills-through-playing-games) are jumbled. 

To make it easier to find a learning game, organize the game links by topics.
Suggested topics to use include: CSS, Coding Concepts, Tools & Coding Helpers.

Each link should be on its own line.

Additionally, please verify the links are still valid.

**Comment by Hyunsujk** [comment]
I want to work on this! @alisaduncan

**Comment by Hyunsujk** [comment]
Please see PR #16
