### ISSUE TITLE
Lynda.com Link Updates

### ISSUE THREAD

**Issue by skduits** [KansasCityWomeninTechnology/LearningResources#5]
In the LearningResources.md file:

- Update MCPL link for Lynda.com to https://www.mymcpl.org/research-and-learning/research-databases/lyndacom 
- Update "Kansas City Library" text to say "Kansas City Public Library"
- Update Kansas City Library link to https://www.kclibrary.org/research-resources/research-databases/lyndacom

**Comment by asantospt** [comment]
Can I take this?

**Comment by skduits** [comment]
@a-santos Thanks for the interest! Looks like a PR addressing the change has already been submitted so we are no longer in need of help. Happy Hacktoberfest!

**Comment by skduits** [comment]
Issue was addressed in #6
